### ISSUE TITLE
Draw the flowchart

### ISSUE THREAD

**Issue by arun-esh** [arun-esh/elevatorSimulation#2]
get the initial Startup Flowchart on how the elevator should take instructions!

**Comment by nysdas** [comment]
Created the initial Flowchart for elevator. I am just focusing on making it simple for the start. Elevator route logic is more complicated than what I Drew. 
![elevatorSimulation](https://user-images.githubusercontent.com/87407216/149632630-f8afb5ae-b8d8-4fb6-b3db-11b722afe520.jpg)
